# repos.toml
# Workspace clones are materialized into ./deps/<name> (gitignored).

[[repo]]
name = "abcdef-testbench"
url  = "https://github.com/phys-sims/abcdef-testbench.git"
ref  = "main"

[[repo]]
name = "abcdef-sim"
url  = "https://github.com/phys-sims/abcdef-sim.git"
ref  = "main"

[[repo]]
name = "phys-pipeline"
url  = "https://github.com/phys-sims/phys-pipeline.git"
ref  = "main"

[[repo]]
name = "cpa-sim"
url  = "https://github.com/phys-sims/phys-pipeline.git"
ref  = "main"

[[repo]]
name = "cpa-testbench"
url  = "https://github.com/phys-sims/phys-pipeline.git"
ref  = "main"
